### ISSUE TITLE
Crossfilter content not updating

### ISSUE THREAD

**Issue by nagarashish** [Wildhoney/EmberCrossfilter#26]
If a new item is added, or an item removed, then the Crossfilter is NOT reflecting the change

**Comment by Wildhoney** [comment]
Thanks for creating this issue. Will need to have a little think about it, because it might need a small API change.

**Comment by Wildhoney** [comment]
I've further investigated this ticket, and it goes deeper than `EmberCrossfilter`. Essentially `crossfilter` has an `add` method to add items to the collection. However, once you've applied some dimensions, adding additional items to the crossfilter doesn't appear to work. Requires some more debugging, because I'm sure Crossfilter isn't meant to be frozen after applying a dimension. I can think of a solution for `EmberCrossfilter`, but I think this issue needs to be focussed more on Crossfilter itself. I'll keep investigating, and speak to Jason Davies (Crossfilter contributor) as well to see what he has to say.
